load_lib vomstest.exp
testheader "See if the library can be linked."

proc mytest {} {
    set ::_buildout [exec mktemp $::SCRATCHDIR/program-out-XXXXXX]
    set res [_buildJava basictest.java]

    if $res then {
        addlog $::_buildout
        set NOJAVALIB "no"
        testmessage "library cannot be linked."
        return $::FAILTEST
    }

    testmessage "library can be linked"
    return $::PASSTEST
}

do_test
