/* soapServer.c
   Generated by gSOAP 2.7.9k from VOMSAC.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.7.9k 2009-02-24 13:26:03 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetAttributeCertificate"))
		return soap_serve___ns1__GetAttributeCertificate(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetAttributeCertificate(struct soap *soap)
{	struct __ns1__GetAttributeCertificate soap_tmp___ns1__GetAttributeCertificate;
	struct _ns1__GetAttributeCertificateResponse ns1__GetAttributeCertificateResponse;
	soap_default__ns1__GetAttributeCertificateResponse(soap, &ns1__GetAttributeCertificateResponse);
	soap_default___ns1__GetAttributeCertificate(soap, &soap_tmp___ns1__GetAttributeCertificate);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetAttributeCertificate(soap, &soap_tmp___ns1__GetAttributeCertificate, "-ns1:GetAttributeCertificate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetAttributeCertificate(soap, soap_tmp___ns1__GetAttributeCertificate.ns1__GetAttributeCertificate, &ns1__GetAttributeCertificateResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__GetAttributeCertificateResponse(soap, &ns1__GetAttributeCertificateResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__GetAttributeCertificateResponse(soap, &ns1__GetAttributeCertificateResponse, "ns1:GetAttributeCertificateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__GetAttributeCertificateResponse(soap, &ns1__GetAttributeCertificateResponse, "ns1:GetAttributeCertificateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapServer.c */
