/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glite_security_voms_peers_VomsdataPeer */

#ifndef _Included_org_glite_security_voms_peers_VomsdataPeer
#define _Included_org_glite_security_voms_peers_VomsdataPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_glite_security_voms_peers_VomsdataPeer_RECURSIVE
#define org_glite_security_voms_peers_VomsdataPeer_RECURSIVE 1L
/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    LoadSystemContacts
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_LoadSystemContacts
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    LoadUserContacts
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_LoadUserContacts
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    FindByAlias
 * Signature: (Ljava/lang/String;)[Lorg/glite/security/voms/peers/ContactDataPeer;
 */
JNIEXPORT jobjectArray JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_FindByAlias
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    FindByVO
 * Signature: (Ljava/lang/String;)[Lorg/glite/security/voms/peers/ContactDataPeer;
 */
JNIEXPORT jobjectArray JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_FindByVO
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    Order
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_Order
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ResetOrder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ResetOrder
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    AddTarget
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_AddTarget
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ListTargets
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ListTargets
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ResetTargets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ResetTargets
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ServerErrors
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ServerErrors
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    RetrieveReal
 * Signature: ([B[[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_RetrieveReal
  (JNIEnv *, jobject, jbyteArray, jobjectArray, jint);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    Contact
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_Contact
  (JNIEnv *, jobject, jstring, jint, jstring, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    SetVerificationType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_SetVerificationType
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    SetLifetime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_SetLifetime
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    Import
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_Import
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ExportReal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ExportReal
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    DefaultDataReal
 * Signature: ()Lorg/glite/security/voms/peers/VomsPeer;
 */
JNIEXPORT jobject JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_DefaultDataReal
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    ErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_ErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_create__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    create
 * Signature: (Lorg/glite/security/voms/peers/VomsdataPeer;)J
 */
JNIEXPORT jlong JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_create__Lorg_glite_security_voms_peers_VomsdataPeer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_glite_security_voms_peers_VomsdataPeer
 * Method:    initializer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsdataPeer_initializer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_glite_security_voms_peers_ContactDataPeer */

#ifndef _Included_org_glite_security_voms_peers_ContactDataPeer
#define _Included_org_glite_security_voms_peers_ContactDataPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glite_security_voms_peers_ContactDataPeer
 * Method:    initializer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_ContactDataPeer_initializer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_glite_security_voms_peers_VomsPeer */

#ifndef _Included_org_glite_security_voms_peers_VomsPeer
#define _Included_org_glite_security_voms_peers_VomsPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glite_security_voms_peers_VomsPeer
 * Method:    initializer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_VomsPeer_initializer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_glite_security_voms_peers_DataPeer */

#ifndef _Included_org_glite_security_voms_peers_DataPeer
#define _Included_org_glite_security_voms_peers_DataPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glite_security_voms_peers_DataPeer
 * Method:    initializer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_DataPeer_initializer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_glite_security_voms_peers_AttributePeer */

#ifndef _Included_org_glite_security_voms_peers_AttributePeer
#define _Included_org_glite_security_voms_peers_AttributePeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glite_security_voms_peers_AttributePeer
 * Method:    initializer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_AttributePeer_initializer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_glite_security_voms_peers_AttributeListPeer */

#ifndef _Included_org_glite_security_voms_peers_AttributeListPeer
#define _Included_org_glite_security_voms_peers_AttributeListPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glite_security_voms_peers_AttributeListPeer
 * Method:    initializer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_glite_security_voms_peers_AttributeListPeer_initializer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
