'\" t
.\"     Title: voms-proxy-destroy
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/03/2021
.\"    Manual: VOMS Proxy Destroyer
.\"    Source: VOMS Proxy Destroyer
.\"  Language: English
.\"
.TH "VOMS\-PROXY\-DESTROY" "1" "05/03/2021" "VOMS Proxy Destroyer" "VOMS Proxy Destroyer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
voms-proxy-destroy \- destroys a VOMS proxy
.SH "SYNOPSIS"
.HP \w'\fBvoms\-proxy\-destroy\fR\ 'u
\fBvoms\-proxy\-destroy\fR [options]
.SH "DESCRIPTION"
.PP
The voms\-proxy\-destroy is intended to be used after a proxy is no longer useful, to destroy it
.SH "OPTIONS"
.PP
Options may be specified indifferently with either a "\-" or "\-\-" prefix\&. The options from \-help to \-out are present for compatibility with grid\-proxy\-init, and have the exact same meaning\&. The meaning of the other ones is the following\&.
.PP
\fB\-help\fR
Displays usage
.PP
\fB\-version\fR
Displays version
.PP
\fB\-debug\fR
Enables extra debug output
.PP
\fB\-q\fR
Quiet mode, minimal output
.PP
\fB\-file\fR
\fIproxyfile\fR
The name of the file containing the proxy, in case it is in a non\-standard place\&.
.PP
\fB\-dry\fR
Doesn\*(Aqt actually destroy the proxy\&.
.PP
\fB\-conf\fR
\fIfile\fR
Read options from
\fIfile\fR\&.
.SH "BUGS"
.PP
\m[blue]\fBEGEE Bug Tracking Tool\fR\m[]\&\s-2\u[1]\d\s+2
.SH "SEE ALSO"
.PP
voms\-proxy\-init(1), voms\-proxy\-info(1)
.PP
\m[blue]\fBEDT Auth Home page\fR\m[]\&\s-2\u[2]\d\s+2
.PP
\m[blue]\fBCVSweb\fR\m[]\&\s-2\u[3]\d\s+2
.PP
\m[blue]\fBRPM repository\fR\m[]\&\s-2\u[4]\d\s+2
.SH "AUTHORS"
.PP
Vincenzo Ciaschini
<Vincenzo\&.Ciaschini@cnaf\&.infn\&.it>\&.
.PP
Valerio Venturi
<Valerio\&.Venturi@cnaf\&.infn\&.it>\&.
.SH "COPYRIGHT"
.PP
Copyright (c) Members of the EGEE Collaboration\&. 2004\&. See the beneficiaries list for details on the copyright holders\&.
.PP
Licensed under the Apache License, Version 2\&.0 (the "License"); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
\m[blue]\fBwww\&.apache\&.org/licenses/LICENSE\-2\&.0\fR\m[]\&\s-2\u[5]\d\s+2
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.SH "NOTES"
.IP " 1." 4
EGEE Bug Tracking Tool
.RS 4
\%https://savannah.cern.ch/projects/jra1mdw/
.RE
.IP " 2." 4
EDT Auth Home page
.RS 4
\%http://grid-auth.infn.it
.RE
.IP " 3." 4
CVSweb
.RS 4
\%http://datagrid.in2p3.fr/cgi-bin/cvsweb.cgi/Auth/voms
.RE
.IP " 4." 4
RPM repository
.RS 4
\%http://datagrid.in2p3.fr/distribution/autobuild/i386-rh7.3
.RE
.IP " 5." 4
www.apache.org/licenses/LICENSE-2.0
.RS 4
\%http://www.apache.org/licenses/LICENSE-2.0
.RE
