'\" t
.\"     Title: voms
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/14/2011
.\"    Manual: VOMS Server
.\"    Source: VOMS Server
.\"  Language: English
.\"
.TH "VOMS" "8" "12/14/2011" "VOMS Server" "VOMS Server"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
voms \- VOMS server
.SH "SYNOPSIS"
.HP \w'\fBvoms\fR\ 'u
\fBvoms\fR [\-foreground] [\-port\ \fIport\fR] [\-backlog\ \fIpnum\fR] [\-logfile\ \fIfile\fR] [\-globusid\ \fIid\fR] [\-globuspwd\ \fIfile\fR] [\-passfile\ \fIfile\fR] [\-x509_cert_dir\ \fIpath\fR] [\-x509_cert_file\ \fIfile\fR] [\-x509_user_cert\ \fIfile\fR] [\-x509_user_key\ \fIfile\fR] [\-x509_user_proxy\ \fIfile\fR] [\-dbname\ \fIname\fR] [\-username\ \fIname\fR] [\-vo\ \fI\ name\fR] [\-timeout\ \fI\ limit\fR] [\-test] [\-conf\ \fI\ file\fR] [\-uri\ \fI\ uri\fR] [\-version] [\-code\ \fIc\fR] [\-loglevel\ \fIlev\fR] [\-logtype\ \fItype\fR] [\-logformat\ \fIstr\fR] [\-logdateformat\ \fIstr\fR] [\-debug] [\-sqlloc\ \fIpath\fR] [\-compat] [\-socktimeout\ \fInum\fR] [\-logmax\ \fInum\fR] [\-newformat] [\-skipcacheck] [\-help] [\-usage] [\-globus\ \fIversion\fR] [\-contactstring\ \fIcontact\fR] [\-mysql\-port\ \fIport\fR] [\-mysql\-socket\ \fIsocket\fR] [\-shortfqans] [\-syslog] [\-base64] [\-nologfile]
.SH "DESCRIPTION"
.PP
VOMS \- Virtual Organization Membership Service\&.
.PP
For the initial setup of the server, run the voms_install_db script as root\&.
.SH "OPTIONS"
.PP
Options may be specified indifferently with either a "\-" or "\-\-" prefix\&. Their meaning is the following\&.
.PP
\fB\-help\fR
.PP
\fB\-usage\fR
.PP
These options print a list of options that the server accepts\&. They are synonyms\&.
.PP
\fB\-foreground\fR
.PP
Runs part of the server in foreground\&. Easier debugging\&.
.PP
\fB\-port\fR
\fIport\fR
.PP
Listens on port
\fIport\fR\&. The default is 754\&.
.PP
\fB\-backlog\fR
\fInum\fR
.PP
Sets the maximum backlof for the connections\&. The default is 50\&.
.PP
\fB\-logfile\fR
\fIfile\fR
.PP
Selects the file for logging\&. The default is /ver/log/voms\&.
.PP
\fB\-globusid\fR
\fIid\fR
.PP
\fB\-globuspwd\fR
\fIfile\fR
.PP
This options are supported for backwards compatibility only\&. They have no effect, and indeed do not get listed by the \-help option\&.
.PP
\fB\-passfile\fR
\fIfile\fR
.PP
Reads the password to access the DB from
\fIfile\fR\&. The default is to read it from the console during server\'s startup\&.
.PP
\fB\-x509_cert_dir\fR
\fIpath\fR
.PP
\fB\-x509_cert_file\fR
\fIfile\fR
.PP
\fB\-x509_user_cert\fR
\fIfile\fR
.PP
\fB\-x509_user_key\fR
\fIfile\fR
.PP
\fB\-x509_user_proxy\fR
\fIfile\fR
.PP
These options set the respective variables\&.
.PP
\fB\-dbname\fR
\fIname\fR
.PP
Sets the name of the DB\&. Default
\fIvoms\fR\&.
.PP
\fB\-username\fR
\fIname\fR
.PP
Sets the name of the user for the DB login\&. The default is
\fIvoms\fR\&.
.PP
\fB\-vo\fR
\fIname\fR
.PP
Sets the name of the VO that owns this server\&. The default is
\fIunspecified\fR\&.
.PP
\fB\-timeout\fR
\fIlimit\fR
.PP
Sets the length of time that the information is valid, measured in secods\&. The default is 86400 seconds (24 hours)\&.
.PP
\fB\-test\fR
.PP
Prints information about the server startup and then exits\&.
.PP
\fB\-conf\fR
\fIfile\fR
.PP
Reads option from the file
\fIfile\fR\&. The options must be present one per line in the format
\fB\-option[=value]\fR
where the value part must obviously be present only if it is required\&.
.PP
\fB\-uri\fR
\fIuri\fR
.PP
Defines the uri of the server that will be included in the generated pseudo certificate\&. The default value is hostname:port
.PP
\fB\-version\fR
.PP
Prints information about the server and then exits\&.
.PP
\fB\-code\fR
\fIc\fR
.PP
\fB\-globus\fR
\fIversion\fR
.PP
These option are obsolete and only present for backwards compatibility with old installation\&. Currently, their values are ignored\&. Do not specify them in new installations\&.
.PP
\fB\-logtype\fR
\fItype\fR
.PP
Sets the type of messages that will be loggged\&. Acceptable values are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
1 \- STARTUP, print startup messages\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2 \- REQUEST, print messages during the request interpretation phase\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
4 \- RESULT, print messages during the result sending phase\&.
.RE
.PP
This values can be ORed together to indicate that all the corresponding types of messages are required\&. The default values is 255\&.
.PP
\fB\-loglevel\fR
\fIlev\fR
.PP
Sets the level of verbosity of log messages\&. Acceptable values are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
1 \- LEV_NONE, do not log anything\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2 \- LEV_ERROR, the default, logs only error conditions\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
3 \- LEV_WARNINGS, logs also warning messages\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
4 \- LEV_INFO, logs also general informational messages\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
5 \- LEV_DEBUG, logs also a lot of debug messages\&. Setting this level of verbosity overwrites the value of the
\fB\-logtype\fR
option to 255\&.
.RE
.PP
Higher values include all messages printed by lower ones, and values not documented here are translated as the highest level possible, LEV_DEBUG
.PP
\fB\-logformat\fR
\fIstr\fR
.PP
Sets the format used by the loggin system according toa printf\-like format string with the following directives format:
\fI\e%[size][char]\fR
where size, if present, sets the maximum length of the field and
\fIchar\fR
selects the type of substitution done\&. Possible values are the following:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
% \- Substitutes a plain \'%\'\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
d \- Substitutes the date\&. The date format is specified by the
\fB\-logdateformat\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
f \- Substitutes the name of the source file that logs the message\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
F \- Substitutes the name of the function that logs the message\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
h \- Substitutes the hostname of the machine hosting the service\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
l \- Substitutes the line number that logs the message\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
m \- Substitutes the message proper\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
p \- Substitutes the process\' pid\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
s \- Substitutes the service name ("vomsd")\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
t \- Substitutes the number of the message type\&. (see the
\fB\-logtype\fR
option)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
T \- Substitutes the name of the message type\&. (see the
\fB\-logtype\fR
option)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
v \- Substitutes the number of the message level\&. (see the
\fB\-loglevel\fR
option)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
V \- Substitutes the name of the message level\&. (see the
\fB\-loglevel\fR
option)
.RE
.PP
The default value for this options is: "%d:%h:%s(%p):%V:%T:%F (%f:%l):%m"
.PP
\fB\-logdateformat\fR
\fIstr\fR
.PP
This option sets the format used to print the date\&. The format is the same used by the strftime(3) function, and its default value is: "%c"\&.
.PP
\fB\-debug\fR
.PP
This option puts the server into debug mode\&. This mode automatically implies
\fB\-loglevel 5\fR\&. Also, this option hurts scalability and is not suggested in a production environment
.PP
\fB\-sqlloc\fR
\fI/path/file\fR
.PP
This option specifies the full path for the DB access library\&. Please note that there is no default for this option!
.PP
\fB\-socktimeout\fR
\fInum\fR
.PP
This option sets the amount of time, in seconds, after which the server will drop an inactive connection\&. The default is 60 seconds\&.
.PP
\fB\-maxlog\fR
\fInum\fR
.PP
This options sets the maximum size of a log file\&. Please note that this size is approximate, and may be exceeded by a few thousand bytes\&. In any case, when the specified amount is surpassed, logfiles are rotated\&. The default is 10Mb
.PP
\fB\-newformat\fR
.PP
This forces the server to generate ACs in the new (correct) format\&. This is meant as a compatibility feature to ease migration while the servers upgrade to the new version\&.
.PP
\fB\-skipcacheck\fR
.PP
This option, if specified, forces voms to drop some of the checks done as the authorization step before AC creation\&. Specifically, voms will no longer be capable of distinguishing to certificates with the same DN but different issuers\&. For obvious reasons, use of this option is discouraged\&. Note also that activating this option requires a previous check by the voms server administrator that there are no certificates registered in the DB which the same DN and different issuers\&. If there are, the result of a voms\-proxy\-init command for one of those users will be unpredictable\&.
.PP
\fB\-contactstring\fR
\fIcontact\fR
.PP
This string specifies information on how to contact the DB server\&. Its exact meaning depends on the DB backend used\&. For MySQL it is the hostname of the MySQL server, and it defaults to \'localhost\'\&. For Oracle it is the contactstring of the DB\&. However, for oracle it is better to put what whould be the argument of this string into the \'tnsnames\&.ora\' file and ignore this option,
.PP
\fB\-mysql\-port \fR
\fIport\fR
.PP
This option specified the port on which the MySQL server is listening if it is different from its 3306 default\&. This value is ignored for Oracle backends\&.
.PP
\fB\-mysql\-socket\fR
\fIsocket\fR
.PP
MySQL servers may be configured to allow access through a unix\-level socket\&. This option allows to specify this method of contact\&. However, it is almost always better to contact the server through the port\&. This option is ignored for Oracle backends\&.
.PP
\fB\-shortfqans\fR
.PP
This option instructs the server to always generate FQANs in their short form, i\&.e\&. without the /Role=NULL and /Capability=NULL parts\&. Successive server version will make this behaviour the default, and provide a
\fB\-noshortfqans\fR
option to fallback to the longer format\&. Specifying this option is recommended\&.
.PP
\fB\-syslog\fR
.PP
This option allows log messages to be sent to syslog\&.
.PP
\fB\-base64\fR
.PP
This option instructs the server to use the base64 encoding for its messages, rather than the in\-house encoding\&. This option will be made the default in future versions and
\fB\-nobase64\fR
will be provided to fallback to the inhouse encoding\&. Specifying this option is recommended\&.
.PP
\fB\-nologfile\fR
.PP
This option disables logging on the voms specific logfile\&. Please note that specifying this option without at the same time specifying
\fB\-syslog\fR
implies that no logging will take place\&.
.SH "BUGS"
.PP
\m[blue]\fBEGEE Bug Tracking Tool\fR\m[]\&\s-2\u[1]\d\s+2
.SH "SEE ALSO"
.PP
voms\-proxy\-init(1), voms\-proxy\-info(1), voms\-proxy\-destroy(1)
.PP
\m[blue]\fBEDT Auth Home page\fR\m[]\&\s-2\u[2]\d\s+2
.PP
\m[blue]\fBCVSweb\fR\m[]\&\s-2\u[3]\d\s+2
.PP
\m[blue]\fBRPM repository\fR\m[]\&\s-2\u[4]\d\s+2
.SH "AUTHORS"
.PP
Vincenzo Ciaschini
Vincenzo\&.Ciaschini@cnaf\&.infn\&.it\&.
.PP
Valerio Venturi
Valerio\&.Venturi@cnaf\&.infn\&.it\&.
.SH "COPYRIGHT"
.PP
Copyright (c) Members of the EGEE Collaboration\&. 2004\&. See the beneficiaries list for details on the copyright holders\&.
.PP
Licensed under the Apache License, Version 2\&.0 (the "License"); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
\m[blue]\fBwww\&.apache\&.org/licenses/LICENSE\-2\&.0\fR\m[]\&\s-2\u[5]\d\s+2
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.SH "NOTES"
.IP " 1." 4
EGEE Bug Tracking Tool
.RS 4
\%https://savannah.cern.ch/projects/jra1mdw/
.RE
.IP " 2." 4
EDT Auth Home page
.RS 4
\%http://grid-auth.infn.it
.RE
.IP " 3." 4
CVSweb
.RS 4
\%http://datagrid.in2p3.fr/cgi-bin/cvsweb.cgi/Auth/voms
.RE
.IP " 4." 4
RPM repository
.RS 4
\%http://datagrid.in2p3.fr/distribution/autobuild/i386-rh7.3
.RE
.IP " 5." 4
www.apache.org/licenses/LICENSE-2.0
.RS 4
\%http://www.apache.org/licenses/LICENSE-2.0
.RE
