'\" t
.\"     Title: voms-install-replica
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/03/2021
.\"    Manual: VOMS Server Slave setup
.\"    Source: VOMS Server Slave setup
.\"  Language: English
.\"
.TH "VOMS\-INSTALL\-REPLI" "8" "05/03/2021" "VOMS Server Slave setup" "VOMS Server Slave setup"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
voms-install-replica \- Setup the voms server as a slave of a master server
.SH "SYNOPSIS"
.HP \w'\fBvoms_install_replica\fR\ 'u
\fBvoms_install_replica\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
The voms_install_replica script initializes a VOMS server as a slave of a master server\&. It only works if both servers have MySQL as the underlying DB\&.
.SH "OPTIONS"
.PP
\fB\-\-mysql\-home\fR
\fIpath\fR
Default home of MySQL\&. The default is \*(Aq/usr\*(Aq\&.
.PP
\fB\-\-db\fR
\fIname\fR
Name of the db to create\&. It must be the same name used in the \-\-master\-db option\&.
.PP
\fB\-\-mysql\-admin\fR
\fIname\fR
The name of the MySQL admin user\&. The default is \*(Aqroot\*(Aq\&.
.PP
\fB\-\-mysql\-pwd\fR
\fIvalue\fR
The password of the MySQL admin user, The default is to not use a password\&.
.PP
\fB\-\-master\-host\fR
\fIvalue\fR
This is the fully qualified hostname of the master server\&.
.PP
\fB\-\-master\-mysql\-user\fR
\fIvalue\fR
This is the username that the master has made available for the slave to use\&.
.PP
\fB\-\-master\-mysql\-pwd\fR
\fIvalue\fR
This is the password associated to the \-\-master\-mysql\-user account\&.
.PP
\fB\-\-master\-db\fR
\fIvalue\fR
This is the name of the DB on the master\&. It must be the same as the one specified in the \-\-db option\&.
.PP
\fB\-\-master\-log\-file\fR
\fIvalue\fR
This is the name of the file where a copy of the master log file will be placed\&.
.PP
\fB\-\-master\-log\-pos\fR
\fIvalue\fR
This is the location where a copy of the master log file will be placed\&.
.SH "BUGS"
.PP
\m[blue]\fBEGEE Bug Tracking Tool\fR\m[]\&\s-2\u[1]\d\s+2
.SH "SEE ALSO"
.PP
voms(8)
.PP
\m[blue]\fBEDT Auth Home page\fR\m[]\&\s-2\u[2]\d\s+2
.PP
\m[blue]\fBCVSweb\fR\m[]\&\s-2\u[3]\d\s+2
.PP
\m[blue]\fBRPM repository\fR\m[]\&\s-2\u[4]\d\s+2
.SH "AUTHORS"
.PP
Vincenzo Ciaschini
<Vincenzo\&.Ciaschini@cnaf\&.infn\&.it>\&.
.PP
Valerio Venturi
<Valerio\&.Venturi@cnaf\&.infn\&.it>\&.
.SH "COPYRIGHT"
.PP
Copyright (c) Members of the EGEE Collaboration\&. 2004\&. See the beneficiaries list for details on the copyright holders\&.
.PP
Licensed under the Apache License, Version 2\&.0 (the "License"); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
\m[blue]\fBwww\&.apache\&.org/licenses/LICENSE\-2\&.0\fR\m[]\&\s-2\u[5]\d\s+2
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.SH "NOTES"
.IP " 1." 4
EGEE Bug Tracking Tool
.RS 4
\%https://savannah.cern.ch/projects/jra1mdw/
.RE
.IP " 2." 4
EDT Auth Home page
.RS 4
\%http://grid-auth.infn.it
.RE
.IP " 3." 4
CVSweb
.RS 4
\%http://datagrid.in2p3.fr/cgi-bin/cvsweb.cgi/Auth/voms
.RE
.IP " 4." 4
RPM repository
.RS 4
\%http://datagrid.in2p3.fr/distribution/autobuild/i386-rh7.3
.RE
.IP " 5." 4
www.apache.org/licenses/LICENSE-2.0
.RS 4
\%http://www.apache.org/licenses/LICENSE-2.0
.RE
