load_lib vomstest.exp
testheader "See if requesting a too long proxy fails."

proc mytest {} {
    _activateCert mycert2

    _vomsStart voms1
    set res [log_exec outname {voms-proxy-init --voms voms1 --valid 100:00}]
    _vomsStop voms1

    if $res then {
        testmessage "voms-proxy-init correctly failed."
        return $::PASSTEST
    } else {
        addlog $outname
        testmesasge "voms-proxy-init incorrectly suceeded."
        return $::FAILTEST
    }
}

do_test