load_lib vomstest.exp
testheader "See if a normal proxy can be created."

proc mytest {} {
    _activateCert mycert2

    set res [log_exec outname {voms-proxy-init}]

    if $res then {
        addlog $outname
        testmessage "voms-proxy-init returned error message."
        return $::FAILTEST
    } else {
        testmessage "proxy successfully created."
        return $::PASSTEST
    }
}

do_test
