load_lib vomstest.exp
testheader "See if voms-proxy-init --verify works."

proc mytest {} {
    _activateCert mycertrevoked

    _vomsStart voms1
    set res [log_exec outname {voms-proxy-init --voms voms1 --verify}]
    _vomsStop voms1

    if $res then {
        testmessage "certificate detected as revoked."
        return $::PASSTEST
    } else {
        addlog $outname
        testmessage "success with a revoked certificate"
        return $::FAILTEST
    }
}

do_test