load_lib vomstest.exp
testheader "See if voms-proxy-init --ignorewarn works."

proc mytest {} {
    _activateCert mycert2

    _vomsStart voms1
    set res [log_exec outname {voms-proxy-init --voms voms1 --vomslife 1000:00 --ignorewarn}]
    _vomsStop voms1

    if $res then {
        addlog $outname
        testmessage "voms-proxy-init failed."
        return $::FAILTEST
    } else {
        testmessage "voms-proxy-init succeeded."
        return $::PASSTEST
    }
}

do_test
