load_lib vomstest.exp
testheader "Requesting a non-existent role should fail."

proc mytest {} {
    _activateCert mycert2

    _vomsStart voms1
    set res [log_exec outname {voms-proxy-init --voms voms1:/Role=product}]
    _vomsStop voms1

    if $res then {
        testmessage "Failed as expected."
        return $::PASSTEST
    } else {
        addlog $outname
        testmessage "voms-proxy-init succeeded with a non-existent role."
        return $::FAILTEST
    }
}

do_test