load_lib vomstest.exp
testheader "See if voms-proxy-init --old works."

proc mytest {} {
    _activateCert mycert2

    _vomsStart voms1
    set res [log_exec outname {voms-proxy-init --old --voms voms1}]
    _vomsStop voms1
   
    if $res then {
        addlog $outname
        testmessage "voms-proxy-init failed."
        return $::FAILTEST
    } else {
        testmessage "voms-proxy-init succeeded."
        return $::PASSTEST
    }
}


do_test