load_lib vomstest.exp
testheader "See if voms-proxy-init --noregen of an rfc proxy works."

proc mytest {} {
    _activateCert mycert2

    _vomsStart voms1
    set res [log_exec outname {voms-proxy-init --rfc}]
    set res [log_exec outname {voms-proxy-init --valid 01:00 --voms voms1 --noregen}]
    _vomsStop voms1

    if $res then {
        addlog $outname
        testmessage "voms-proxy-init failed."
        return $::FAILTEST
    }

    return $::PASSTEST
}

do_test