load_lib vomstest.exp
testheader "See if the C++ library can be linked."

proc mytest {} {
    set ::_buildout [exec mktemp $::SCRATCHDIR/program-out-XXXXXX]
    set res [_buildCC basictest.cc]

    if $res then {
        addlog $::_buildout
        set ::NOCCLIB "no"
        testmessage "library cannot be linked."
        return $::FAILTEST
    } else {
        testmessage "library can be linked"
        return $::PASSTEST
    }
}

do_test

