name: CI

on:
  pull_request:
  push:

jobs:

  el9:
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          yum install -y epel-release
          yum install -y make file automake libtool gcc-c++ openssl-devel gsoap-devel gsoap expat-devel bison

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make

  ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y make automake libtool pkg-config g++ libssl-dev libgsoap-dev gsoap libexpat-dev

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make

  ubuntu2404:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y make automake libtool pkg-config g++ libssl-dev libgsoap-dev gsoap libexpat-dev

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make

